version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_JWT_SECRET=verySecureSecretKeyForGeneratingJwtTokensInSeuManoelStore
      - APP_JWT_EXPIRATION=86400
